<?php
return [
    'db'=>[
        'dev'=>[
            'host'=>'localhost',
            'database'=>'project_social',
            'username'=>'root',
            'password'=>'',
            'charset'=>'utf8mb4',
            'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
        ],
        'prod'=>[
            'host'=>'localhost',
            'database'=>'project_social',
            'username'=>'root',
            'password'=>'',
            'charset'=>'utf8mb4',
            'select'=>[                
                'host'=>'localhost',
                'database'=>'project_social',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
            ],'delete'=>[
                'host'=>'localhost',
                'database'=>'project_social',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
            ],
            'insert'=>[
                'host'=>'localhost',
                'database'=>'project_social',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
            ],
            'update'=>[
                'host'=>'localhost',
                'database'=>'project_social',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
            ]
        ]
    ]
            ];