<?php
return [
    'db'=>[
        'dev'=>[
            'default'=>[
                'host'=>'localhost',
                'database'=>'auto_db',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
                'auto-generate'=>false,
                'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
            ]
        ],
        'prod'=>[
            'default'=>[
                'host'=>'localhost',
                'database'=>'auto_db',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
                'auto-generate'=>true,
                'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
            ],
            'select'=>[                
                'host'=>'localhost',
                'database'=>'auto_db',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
                'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
            ],
            'delete'=>[
                'host'=>'localhost',
                'database'=>'auto_db',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
                'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
            ],
            'insert'=>[
                'host'=>'localhost',
                'database'=>'auto_db',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
                'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
            ],
            'update'=>[
                'host'=>'localhost',
                'database'=>'auto_db',
                'username'=>'root',
                'password'=>'',
                'charset'=>'utf8mb4',
                'dsn'=>'mysql:host={host};dbname={database};charset={charset}'
            ]
        ]
    ]
];